server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: sample_intranet
  sslmode: disable

jwt:
  secret: your-secret-key-change-this-in-production
  expires_hours: 24

session:
  secret: your-session-secret-change-this-in-production
  name: session_id
  max_age: 86400

log:
  level: info
  format: json
