services:
  # Java Spring Boot 백엔드 애플리케이션
  app:
    build: .
    container_name: sample_intranet_backend_java
    ports:
      - "9090:9090"  # Spring Boot 포트
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sample_intranet_postgres_shared:5432/sample_intranet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production-spring
      JWT_EXPIRATION: 86400000
    networks:
      - shared_network
    depends_on:
      - postgres

  # 공유 PostgreSQL 데이터베이스 참조
  postgres:
    image: postgres:15
    container_name: sample_intranet_postgres_shared
    environment:
      POSTGRES_DB: sample_intranet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_shared_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  postgres_shared_data:

networks:
  shared_network:
    driver: bridge 