services:
  # Python 백엔드 애플리케이션
  app:
    build: .
    container_name: sample_intranet_backend_python
    ports:
      - "8000:8000"  # FastAPI 기본 포트
    environment:
      DATABASE_URL: postgresql://postgres:password@sample_intranet_postgres_shared:5432/sample_intranet
      JWT_SECRET: your-jwt-secret-change-this-in-production
      JWT_EXPIRES_HOURS: 24
    volumes:
      - .:/app  # 개발 시 코드 변경 실시간 반영
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - shared_network
    depends_on:
      - postgres

  # 공유 PostgreSQL 데이터베이스 참조
  postgres:
    image: postgres:15
    container_name: sample_intranet_postgres_shared
    environment:
      POSTGRES_DB: sample_intranet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_shared_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  postgres_shared_data:

networks:
  shared_network:
    driver: bridge 